sap.ui.define([
	"sap/ui/test/Opa5",
	"sap/ui/test/actions/Press",
    "sap/ui/test/matchers/AggregationLengthEquals"
], function (Opa5, Press, AggregationLengthEquals) {
	"use strict";

	var sViewName = "TicketList";

	Opa5.createPageObjects({
		onTheListReport: {
			actions: {},
			assertions: {
				iShouldSeeTheTable: function () {
					return this.waitFor({
						controlType: "sap.m.Table",
						viewName: "sap.fe.templates.ListReport.ListReport",
                        // We don't know the exact view ID generated by FE, but the viewName for the template is standard
						success: function (aTables) {
							Opa5.assert.ok(aTables.length > 0, "Found the List Report Table");
						},
						errorMessage: "Could not find the List Report Table"
					});
				}
			}
		}
	});
});