REPORT z_ticketum_smoke_test.

DATA: ls_header  TYPE zticket_hdr,
      ls_item    TYPE zticket_itm,
      ls_comment TYPE zticket_cmt,
      lv_number  TYPE char10,
      lv_rc      TYPE sysubrc.

* 1. Get Number
CALL FUNCTION 'NUMBER_GET_NEXT'
  EXPORTING
    nr_range_nr             = '01'
    object                  = 'Z_TICKET_ID'
  IMPORTING
    number                  = lv_number
    returncode              = lv_rc
  EXCEPTIONS
    OTHERS                  = 1.

IF sy-subrc <> 0.
  WRITE: / 'Error getting number range value.'.
ELSE.
  WRITE: / 'Generated Number:', lv_number.
ENDIF.

* 2. Prepare Data
TRY.
    ls_header-client = sy-mandt.
    ls_header-ticket_id = cl_system_uuid=>create_uuid_x16_static( ).
    ls_header-title = 'Smoke Test Ticket'.
    ls_header-description = 'This is a test ticket generated by smoke test.'.
    ls_header-priority = '1'. " High
    ls_header-status = '01'. " Open
    GET TIME STAMP FIELD ls_header-created_at.
    ls_header-created_by = sy-uname.

    ls_item-client = sy-mandt.
    ls_item-ticket_id = ls_header-ticket_id.
    ls_item-item_no = '0010'.
    ls_item-description = 'Test Item'.
    ls_item-status = '01'.
    ls_item-planned_effort_hr = '1.5'.

    ls_comment-client = sy-mandt.
    ls_comment-ticket_id = ls_header-ticket_id.
    ls_comment-comment_id = cl_system_uuid=>create_uuid_x16_static( ).
    ls_comment-comment_text = 'This is a test comment.'.
    GET TIME STAMP FIELD ls_comment-created_at.
    ls_comment-created_by = sy-uname.

* 3. Insert Data
    INSERT zticket_hdr FROM ls_header.
    IF sy-subrc = 0.
      WRITE: / 'Header inserted successfully. ID:', ls_header-ticket_id.
    ELSE.
      WRITE: / 'Error inserting header.'.
    ENDIF.

    INSERT zticket_itm FROM ls_item.
    IF sy-subrc = 0.
      WRITE: / 'Item inserted successfully.'.
    ELSE.
      WRITE: / 'Error inserting item.'.
    ENDIF.

    INSERT zticket_cmt FROM ls_comment.
    IF sy-subrc = 0.
      WRITE: / 'Comment inserted successfully.'.
    ELSE.
      WRITE: / 'Error inserting comment.'.
    ENDIF.

* 4. Read Back
    CLEAR ls_header.
    SELECT SINGLE * FROM zticket_hdr INTO ls_header WHERE ticket_id = ls_item-ticket_id.
    IF sy-subrc = 0.
      WRITE: / 'Read back Header: ', ls_header-title.
    ELSE.
      WRITE: / 'Error reading back header.'.
    ENDIF.

  CATCH cx_uuid_error.
    WRITE: / 'UUID Error'.
ENDTRY.

ROLLBACK WORK. " Clean up
WRITE: / 'Test complete. Rolled back changes.'.
